language: ruby
cache: bundler
rvm:
  - 2.4.5
  - 2.5.5
  - 2.6.2 # Uses unicode 12.0.0
  - 2.6.3 # Uses unicode 12.1.0
  - 2.7.2
  - 3.0.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
