require 'pstore'

module RegexpExamples
  class UnicodeCharRanges

    # These values were generated by: scripts/unicode_lister.rb
    # Note: Only the first 128 results are listed, for performance.
    # Also, some groups seem to have no matches (weird!)
    STORE_FILENAME = 'unicode_ranges.pstore'

    attr_reader :range_store, :store_location

    def initialize(location="db/#{STORE_FILENAME}")
      @store_location = location
    end

    def get(key)
      range_store.transaction(true) do
        ranges_to_unicode(range_store[key])
      end
    end

    alias_method :[], :get

    private

    def ranges_to_unicode(ranges)
      result = []
      ranges.each do |range|
        if range.is_a? Fixnum # Small hack to improve readability below
          result << hex_to_unicode(range.to_s(16))
        else
          range.each { |num| result << hex_to_unicode(num.to_s(16)) }
        end
      end
      result
    end

    def hex_to_unicode(hex)
      eval("?\\u{#{hex}}")
    end

    def range_store
      @range_store ||= PStore.new(store_location)
    end
  end
end
